// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Example

import "strconv"

type Equipment byte

const (
	EquipmentNONE      Equipment = 0
	EquipmentMuLan     Equipment = 1
	EquipmentWeapon    Equipment = 2
	EquipmentGun       Equipment = 3
	EquipmentSpaceShip Equipment = 4
	EquipmentOther     Equipment = 5

	EquipmentVerifyValueMin Equipment = 0
	EquipmentVerifyValueMax Equipment = 5
)

var EnumNamesEquipment = map[Equipment]string{
	EquipmentNONE:      "NONE",
	EquipmentMuLan:     "MuLan",
	EquipmentWeapon:    "Weapon",
	EquipmentGun:       "Gun",
	EquipmentSpaceShip: "SpaceShip",
	EquipmentOther:     "Other",
}

var EnumValuesEquipment = map[string]Equipment{
	"NONE":      EquipmentNONE,
	"MuLan":     EquipmentMuLan,
	"Weapon":    EquipmentWeapon,
	"Gun":       EquipmentGun,
	"SpaceShip": EquipmentSpaceShip,
	"Other":     EquipmentOther,
}

func (v Equipment) String() string {
	if s, ok := EnumNamesEquipment[v]; ok {
		return s
	}
	return "Equipment(" + strconv.FormatInt(int64(v), 10) + ")"
}
