// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sample

import (
	"strconv"

	flatbuffers "github.com/tsingson/goflatbuffers/go"
)

type Equipment byte

const (
	EquipmentNONE   Equipment = 0
	EquipmentWeapon Equipment = 1

	EquipmentVerifyValueMin Equipment = 0
	EquipmentVerifyValueMax Equipment = 1
)

var EnumNamesEquipment = map[Equipment]string{
	EquipmentNONE:   "NONE",
	EquipmentWeapon: "Weapon",
}

var EnumValuesEquipment = map[string]Equipment{
	"NONE":   EquipmentNONE,
	"Weapon": EquipmentWeapon,
}

func (v Equipment) String() string {
	if s, ok := EnumNamesEquipment[v]; ok {
		return s
	}
	return "Equipment(" + strconv.FormatInt(int64(v), 10) + ")"
}

type EquipmentT struct {
	Type  Equipment
	Value interface{}
}

func (t *EquipmentT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case EquipmentWeapon:
		return t.Value.(*WeaponT).Pack(builder)
	}
	return 0
}

// UnPack use for single union field
func (rcv Equipment) UnPack(table flatbuffers.Table) *EquipmentT {
	switch rcv {
	case EquipmentWeapon:
		x := GetTableAsWeapon(&table)
		return &EquipmentT{Type: EquipmentWeapon, Value: x.UnPack()}
	}
	return nil
}

// UnPackVector use for vector of unions
func (rcv Equipment) UnPackVector(table flatbuffers.Table) *EquipmentT {
	switch rcv {
	case EquipmentWeapon:
		x := GetTableVectorAsWeapon(&table)
		return &EquipmentT{Type: EquipmentWeapon, Value: x.UnPack()}
	}
	return nil
}
