// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MYGAME_MYGAME_H_
#define FLATBUFFERS_GENERATED_MYGAME_MYGAME_H_

#include "flatbuffers/flatbuffers.h"

namespace weapons {

struct Gun;
struct GunBuilder;
struct GunT;

struct Master;
struct MasterBuilder;
struct MasterT;

}  // namespace weapons

namespace MyGame {
namespace Sample {

struct Vec3;

struct Monster;
struct MonsterBuilder;
struct MonsterT;

struct Weapon;
struct WeaponBuilder;
struct WeaponT;

}  // namespace Sample

struct MyGame;
struct MyGameBuilder;
struct MyGameT;

namespace Sample {

enum Color {
  Color_Red = 0,
  Color_Green = 1,
  Color_Blue = 2,
  Color_MIN = Color_Red,
  Color_MAX = Color_Blue
};

inline const Color (&EnumValuesColor())[3] {
  static const Color values[] = {
    Color_Red,
    Color_Green,
    Color_Blue
  };
  return values;
}

inline const char * const *EnumNamesColor() {
  static const char * const names[4] = {
    "Red",
    "Green",
    "Blue",
    nullptr
  };
  return names;
}

inline const char *EnumNameColor(Color e) {
  if (flatbuffers::IsOutRange(e, Color_Red, Color_Blue)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColor()[index];
}

enum Equipment {
  Equipment_NONE = 0,
  Equipment_MuLan = 1,
  Equipment_Weapon = 2,
  Equipment_Gun = 3,
  Equipment_MIN = Equipment_NONE,
  Equipment_MAX = Equipment_Gun
};

inline const Equipment (&EnumValuesEquipment())[4] {
  static const Equipment values[] = {
    Equipment_NONE,
    Equipment_MuLan,
    Equipment_Weapon,
    Equipment_Gun
  };
  return values;
}

inline const char * const *EnumNamesEquipment() {
  static const char * const names[5] = {
    "NONE",
    "MuLan",
    "Weapon",
    "Gun",
    nullptr
  };
  return names;
}

inline const char *EnumNameEquipment(Equipment e) {
  if (flatbuffers::IsOutRange(e, Equipment_NONE, Equipment_Gun)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEquipment()[index];
}

struct EquipmentUnion {
  Equipment type;
  void *value;

  EquipmentUnion() : type(Equipment_NONE), value(nullptr) {}
  EquipmentUnion(EquipmentUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Equipment_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  EquipmentUnion(const EquipmentUnion &);
  EquipmentUnion &operator=(const EquipmentUnion &u)
    { EquipmentUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  EquipmentUnion &operator=(EquipmentUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~EquipmentUnion() { Reset(); }

  void Reset();

  static void *UnPack(const void *obj, Equipment type, const flatbuffers::resolver_function_t *resolver);
  flatbuffers::Offset<void> Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  MyGame::Sample::WeaponT *AsMuLan() {
    return type == Equipment_MuLan ?
      reinterpret_cast<MyGame::Sample::WeaponT *>(value) : nullptr;
  }
  const MyGame::Sample::WeaponT *AsMuLan() const {
    return type == Equipment_MuLan ?
      reinterpret_cast<const MyGame::Sample::WeaponT *>(value) : nullptr;
  }
  MyGame::Sample::WeaponT *AsWeapon() {
    return type == Equipment_Weapon ?
      reinterpret_cast<MyGame::Sample::WeaponT *>(value) : nullptr;
  }
  const MyGame::Sample::WeaponT *AsWeapon() const {
    return type == Equipment_Weapon ?
      reinterpret_cast<const MyGame::Sample::WeaponT *>(value) : nullptr;
  }
  weapons::GunT *AsGun() {
    return type == Equipment_Gun ?
      reinterpret_cast<weapons::GunT *>(value) : nullptr;
  }
  const weapons::GunT *AsGun() const {
    return type == Equipment_Gun ?
      reinterpret_cast<const weapons::GunT *>(value) : nullptr;
  }
};

bool VerifyEquipment(flatbuffers::Verifier &verifier, const void *obj, Equipment type);
bool VerifyEquipmentVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

}  // namespace Sample

enum Character {
  Character_NONE = 0,
  Character_weapon = 1,
  Character_Monster = 2,
  Character_MIN = Character_NONE,
  Character_MAX = Character_Monster
};

inline const Character (&EnumValuesCharacter())[3] {
  static const Character values[] = {
    Character_NONE,
    Character_weapon,
    Character_Monster
  };
  return values;
}

inline const char * const *EnumNamesCharacter() {
  static const char * const names[4] = {
    "NONE",
    "weapon",
    "Monster",
    nullptr
  };
  return names;
}

inline const char *EnumNameCharacter(Character e) {
  if (flatbuffers::IsOutRange(e, Character_NONE, Character_Monster)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCharacter()[index];
}

template<typename T> struct CharacterTraits {
  static const Character enum_value = Character_NONE;
};

template<> struct CharacterTraits<weapons::Gun> {
  static const Character enum_value = Character_weapon;
};

template<> struct CharacterTraits<MyGame::Sample::Monster> {
  static const Character enum_value = Character_Monster;
};

struct CharacterUnion {
  Character type;
  void *value;

  CharacterUnion() : type(Character_NONE), value(nullptr) {}
  CharacterUnion(CharacterUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Character_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  CharacterUnion(const CharacterUnion &);
  CharacterUnion &operator=(const CharacterUnion &u)
    { CharacterUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  CharacterUnion &operator=(CharacterUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~CharacterUnion() { Reset(); }

  void Reset();

#ifndef FLATBUFFERS_CPP98_STL
  template <typename T>
  void Set(T&& val) {
    using RT = typename std::remove_reference<T>::type;
    Reset();
    type = CharacterTraits<typename RT::TableType>::enum_value;
    if (type != Character_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }
#endif  // FLATBUFFERS_CPP98_STL

  static void *UnPack(const void *obj, Character type, const flatbuffers::resolver_function_t *resolver);
  flatbuffers::Offset<void> Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  weapons::GunT *Asweapon() {
    return type == Character_weapon ?
      reinterpret_cast<weapons::GunT *>(value) : nullptr;
  }
  const weapons::GunT *Asweapon() const {
    return type == Character_weapon ?
      reinterpret_cast<const weapons::GunT *>(value) : nullptr;
  }
  MyGame::Sample::MonsterT *AsMonster() {
    return type == Character_Monster ?
      reinterpret_cast<MyGame::Sample::MonsterT *>(value) : nullptr;
  }
  const MyGame::Sample::MonsterT *AsMonster() const {
    return type == Character_Monster ?
      reinterpret_cast<const MyGame::Sample::MonsterT *>(value) : nullptr;
  }
};

bool VerifyCharacter(flatbuffers::Verifier &verifier, const void *obj, Character type);
bool VerifyCharacterVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

namespace Sample {

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3() {
    memset(static_cast<void *>(this), 0, sizeof(Vec3));
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

}  // namespace Sample
}  // namespace MyGame

namespace weapons {

struct GunT : public flatbuffers::NativeTable {
  typedef Gun TableType;
  int16_t damage;
  bool bool_;
  std::string name;
  std::vector<std::string> names;
  GunT()
      : damage(0),
        bool_(false) {
  }
};

struct Gun FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GunT NativeTableType;
  typedef GunBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DAMAGE = 4,
    VT_BOOL_ = 6,
    VT_NAME = 8,
    VT_NAMES = 10
  };
  int16_t damage() const {
    return GetField<int16_t>(VT_DAMAGE, 0);
  }
  bool bool_() const {
    return GetField<uint8_t>(VT_BOOL_, 0) != 0;
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *names() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_NAMES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_DAMAGE) &&
           VerifyField<uint8_t>(verifier, VT_BOOL_) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_NAMES) &&
           verifier.VerifyVector(names()) &&
           verifier.VerifyVectorOfStrings(names()) &&
           verifier.EndTable();
  }
  GunT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GunT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Gun> Pack(flatbuffers::FlatBufferBuilder &_fbb, const GunT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GunBuilder {
  typedef Gun Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_damage(int16_t damage) {
    fbb_.AddElement<int16_t>(Gun::VT_DAMAGE, damage, 0);
  }
  void add_bool_(bool bool_) {
    fbb_.AddElement<uint8_t>(Gun::VT_BOOL_, static_cast<uint8_t>(bool_), 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Gun::VT_NAME, name);
  }
  void add_names(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names) {
    fbb_.AddOffset(Gun::VT_NAMES, names);
  }
  explicit GunBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Gun> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Gun>(end);
    return o;
  }
};

inline flatbuffers::Offset<Gun> CreateGun(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t damage = 0,
    bool bool_ = false,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names = 0) {
  GunBuilder builder_(_fbb);
  builder_.add_names(names);
  builder_.add_name(name);
  builder_.add_damage(damage);
  builder_.add_bool_(bool_);
  return builder_.Finish();
}

inline flatbuffers::Offset<Gun> CreateGunDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t damage = 0,
    bool bool_ = false,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *names = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto names__ = names ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*names) : 0;
  return weapons::CreateGun(
      _fbb,
      damage,
      bool_,
      name__,
      names__);
}

flatbuffers::Offset<Gun> CreateGun(flatbuffers::FlatBufferBuilder &_fbb, const GunT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MasterT : public flatbuffers::NativeTable {
  typedef Master TableType;
  MasterT() {
  }
};

struct Master FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MasterT NativeTableType;
  typedef MasterBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  MasterT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MasterT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Master> Pack(flatbuffers::FlatBufferBuilder &_fbb, const MasterT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MasterBuilder {
  typedef Master Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit MasterBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Master> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Master>(end);
    return o;
  }
};

inline flatbuffers::Offset<Master> CreateMaster(
    flatbuffers::FlatBufferBuilder &_fbb) {
  MasterBuilder builder_(_fbb);
  return builder_.Finish();
}

flatbuffers::Offset<Master> CreateMaster(flatbuffers::FlatBufferBuilder &_fbb, const MasterT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace weapons

namespace MyGame {
namespace Sample {

struct MonsterT : public flatbuffers::NativeTable {
  typedef Monster TableType;
  std::unique_ptr<MyGame::Sample::Vec3> pos;
  int16_t mana;
  int16_t hp;
  std::string name;
  std::vector<std::string> names;
  std::vector<uint8_t> inventory;
  MyGame::Sample::Color color;
  std::vector<std::unique_ptr<MyGame::Sample::WeaponT>> weapons;
  MyGame::Sample::EquipmentUnion equipped;
  std::vector<MyGame::Sample::Vec3> path;
  MonsterT()
      : mana(150),
        hp(100),
        color(MyGame::Sample::Color_Blue) {
  }
};

struct Monster FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MonsterT NativeTableType;
  typedef MonsterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4,
    VT_MANA = 6,
    VT_HP = 8,
    VT_NAME = 10,
    VT_NAMES = 12,
    VT_INVENTORY = 16,
    VT_COLOR = 18,
    VT_WEAPONS = 20,
    VT_EQUIPPED_TYPE = 22,
    VT_EQUIPPED = 24,
    VT_PATH = 26
  };
  const MyGame::Sample::Vec3 *pos() const {
    return GetStruct<const MyGame::Sample::Vec3 *>(VT_POS);
  }
  int16_t mana() const {
    return GetField<int16_t>(VT_MANA, 150);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 100);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *names() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_NAMES);
  }
  const flatbuffers::Vector<uint8_t> *inventory() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_INVENTORY);
  }
  MyGame::Sample::Color color() const {
    return static_cast<MyGame::Sample::Color>(GetField<int8_t>(VT_COLOR, 2));
  }
  const flatbuffers::Vector<flatbuffers::Offset<MyGame::Sample::Weapon>> *weapons() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<MyGame::Sample::Weapon>> *>(VT_WEAPONS);
  }
  MyGame::Sample::Equipment equipped_type() const {
    return static_cast<MyGame::Sample::Equipment>(GetField<uint8_t>(VT_EQUIPPED_TYPE, 0));
  }
  const void *equipped() const {
    return GetPointer<const void *>(VT_EQUIPPED);
  }
  const MyGame::Sample::Weapon *equipped_as_MuLan() const {
    return equipped_type() == MyGame::Sample::Equipment_MuLan ? static_cast<const MyGame::Sample::Weapon *>(equipped()) : nullptr;
  }
  const MyGame::Sample::Weapon *equipped_as_Weapon() const {
    return equipped_type() == MyGame::Sample::Equipment_Weapon ? static_cast<const MyGame::Sample::Weapon *>(equipped()) : nullptr;
  }
  const weapons::Gun *equipped_as_Gun() const {
    return equipped_type() == MyGame::Sample::Equipment_Gun ? static_cast<const weapons::Gun *>(equipped()) : nullptr;
  }
  const flatbuffers::Vector<const MyGame::Sample::Vec3 *> *path() const {
    return GetPointer<const flatbuffers::Vector<const MyGame::Sample::Vec3 *> *>(VT_PATH);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<MyGame::Sample::Vec3>(verifier, VT_POS) &&
           VerifyField<int16_t>(verifier, VT_MANA) &&
           VerifyField<int16_t>(verifier, VT_HP) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_NAMES) &&
           verifier.VerifyVector(names()) &&
           verifier.VerifyVectorOfStrings(names()) &&
           VerifyOffset(verifier, VT_INVENTORY) &&
           verifier.VerifyVector(inventory()) &&
           VerifyField<int8_t>(verifier, VT_COLOR) &&
           VerifyOffset(verifier, VT_WEAPONS) &&
           verifier.VerifyVector(weapons()) &&
           verifier.VerifyVectorOfTables(weapons()) &&
           VerifyField<uint8_t>(verifier, VT_EQUIPPED_TYPE) &&
           VerifyOffset(verifier, VT_EQUIPPED) &&
           VerifyEquipment(verifier, equipped(), equipped_type()) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyVector(path()) &&
           verifier.EndTable();
  }
  MonsterT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MonsterT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Monster> Pack(flatbuffers::FlatBufferBuilder &_fbb, const MonsterT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MonsterBuilder {
  typedef Monster Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pos(const MyGame::Sample::Vec3 *pos) {
    fbb_.AddStruct(Monster::VT_POS, pos);
  }
  void add_mana(int16_t mana) {
    fbb_.AddElement<int16_t>(Monster::VT_MANA, mana, 150);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(Monster::VT_HP, hp, 100);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Monster::VT_NAME, name);
  }
  void add_names(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names) {
    fbb_.AddOffset(Monster::VT_NAMES, names);
  }
  void add_inventory(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> inventory) {
    fbb_.AddOffset(Monster::VT_INVENTORY, inventory);
  }
  void add_color(MyGame::Sample::Color color) {
    fbb_.AddElement<int8_t>(Monster::VT_COLOR, static_cast<int8_t>(color), 2);
  }
  void add_weapons(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<MyGame::Sample::Weapon>>> weapons) {
    fbb_.AddOffset(Monster::VT_WEAPONS, weapons);
  }
  void add_equipped_type(MyGame::Sample::Equipment equipped_type) {
    fbb_.AddElement<uint8_t>(Monster::VT_EQUIPPED_TYPE, static_cast<uint8_t>(equipped_type), 0);
  }
  void add_equipped(flatbuffers::Offset<void> equipped) {
    fbb_.AddOffset(Monster::VT_EQUIPPED, equipped);
  }
  void add_path(flatbuffers::Offset<flatbuffers::Vector<const MyGame::Sample::Vec3 *>> path) {
    fbb_.AddOffset(Monster::VT_PATH, path);
  }
  explicit MonsterBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Monster> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Monster>(end);
    return o;
  }
};

inline flatbuffers::Offset<Monster> CreateMonster(
    flatbuffers::FlatBufferBuilder &_fbb,
    const MyGame::Sample::Vec3 *pos = 0,
    int16_t mana = 150,
    int16_t hp = 100,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> inventory = 0,
    MyGame::Sample::Color color = MyGame::Sample::Color_Blue,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<MyGame::Sample::Weapon>>> weapons = 0,
    MyGame::Sample::Equipment equipped_type = MyGame::Sample::Equipment_NONE,
    flatbuffers::Offset<void> equipped = 0,
    flatbuffers::Offset<flatbuffers::Vector<const MyGame::Sample::Vec3 *>> path = 0) {
  MonsterBuilder builder_(_fbb);
  builder_.add_path(path);
  builder_.add_equipped(equipped);
  builder_.add_weapons(weapons);
  builder_.add_inventory(inventory);
  builder_.add_names(names);
  builder_.add_name(name);
  builder_.add_pos(pos);
  builder_.add_hp(hp);
  builder_.add_mana(mana);
  builder_.add_equipped_type(equipped_type);
  builder_.add_color(color);
  return builder_.Finish();
}

inline flatbuffers::Offset<Monster> CreateMonsterDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const MyGame::Sample::Vec3 *pos = 0,
    int16_t mana = 150,
    int16_t hp = 100,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *names = nullptr,
    const std::vector<uint8_t> *inventory = nullptr,
    MyGame::Sample::Color color = MyGame::Sample::Color_Blue,
    const std::vector<flatbuffers::Offset<MyGame::Sample::Weapon>> *weapons = nullptr,
    MyGame::Sample::Equipment equipped_type = MyGame::Sample::Equipment_NONE,
    flatbuffers::Offset<void> equipped = 0,
    const std::vector<MyGame::Sample::Vec3> *path = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto names__ = names ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*names) : 0;
  auto inventory__ = inventory ? _fbb.CreateVector<uint8_t>(*inventory) : 0;
  auto weapons__ = weapons ? _fbb.CreateVector<flatbuffers::Offset<MyGame::Sample::Weapon>>(*weapons) : 0;
  auto path__ = path ? _fbb.CreateVectorOfStructs<MyGame::Sample::Vec3>(*path) : 0;
  return MyGame::Sample::CreateMonster(
      _fbb,
      pos,
      mana,
      hp,
      name__,
      names__,
      inventory__,
      color,
      weapons__,
      equipped_type,
      equipped,
      path__);
}

flatbuffers::Offset<Monster> CreateMonster(flatbuffers::FlatBufferBuilder &_fbb, const MonsterT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct WeaponT : public flatbuffers::NativeTable {
  typedef Weapon TableType;
  std::string name;
  int16_t damage;
  WeaponT()
      : damage(0) {
  }
};

struct Weapon FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef WeaponT NativeTableType;
  typedef WeaponBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DAMAGE = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  int16_t damage() const {
    return GetField<int16_t>(VT_DAMAGE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int16_t>(verifier, VT_DAMAGE) &&
           verifier.EndTable();
  }
  WeaponT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(WeaponT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Weapon> Pack(flatbuffers::FlatBufferBuilder &_fbb, const WeaponT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct WeaponBuilder {
  typedef Weapon Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Weapon::VT_NAME, name);
  }
  void add_damage(int16_t damage) {
    fbb_.AddElement<int16_t>(Weapon::VT_DAMAGE, damage, 0);
  }
  explicit WeaponBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Weapon> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Weapon>(end);
    return o;
  }
};

inline flatbuffers::Offset<Weapon> CreateWeapon(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    int16_t damage = 0) {
  WeaponBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_damage(damage);
  return builder_.Finish();
}

inline flatbuffers::Offset<Weapon> CreateWeaponDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int16_t damage = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return MyGame::Sample::CreateWeapon(
      _fbb,
      name__,
      damage);
}

flatbuffers::Offset<Weapon> CreateWeapon(flatbuffers::FlatBufferBuilder &_fbb, const WeaponT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace Sample

struct MyGameT : public flatbuffers::NativeTable {
  typedef MyGame TableType;
  MyGame::CharacterUnion Characters;
  MyGameT() {
  }
};

struct MyGame FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MyGameT NativeTableType;
  typedef MyGameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHARACTERS_TYPE = 4,
    VT_CHARACTERS = 6
  };
  MyGame::Character Characters_type() const {
    return static_cast<MyGame::Character>(GetField<uint8_t>(VT_CHARACTERS_TYPE, 0));
  }
  const void *Characters() const {
    return GetPointer<const void *>(VT_CHARACTERS);
  }
  template<typename T> const T *Characters_as() const;
  const weapons::Gun *Characters_as_weapon() const {
    return Characters_type() == MyGame::Character_weapon ? static_cast<const weapons::Gun *>(Characters()) : nullptr;
  }
  const MyGame::Sample::Monster *Characters_as_Monster() const {
    return Characters_type() == MyGame::Character_Monster ? static_cast<const MyGame::Sample::Monster *>(Characters()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CHARACTERS_TYPE) &&
           VerifyOffset(verifier, VT_CHARACTERS) &&
           VerifyCharacter(verifier, Characters(), Characters_type()) &&
           verifier.EndTable();
  }
  MyGameT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MyGameT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<MyGame> Pack(flatbuffers::FlatBufferBuilder &_fbb, const MyGameT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const weapons::Gun *MyGame::Characters_as<weapons::Gun>() const {
  return Characters_as_weapon();
}

template<> inline const MyGame::Sample::Monster *MyGame::Characters_as<MyGame::Sample::Monster>() const {
  return Characters_as_Monster();
}

struct MyGameBuilder {
  typedef MyGame Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Characters_type(MyGame::Character Characters_type) {
    fbb_.AddElement<uint8_t>(MyGame::VT_CHARACTERS_TYPE, static_cast<uint8_t>(Characters_type), 0);
  }
  void add_Characters(flatbuffers::Offset<void> Characters) {
    fbb_.AddOffset(MyGame::VT_CHARACTERS, Characters);
  }
  explicit MyGameBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MyGame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MyGame>(end);
    return o;
  }
};

inline flatbuffers::Offset<MyGame> CreateMyGame(
    flatbuffers::FlatBufferBuilder &_fbb,
    MyGame::Character Characters_type = MyGame::Character_NONE,
    flatbuffers::Offset<void> Characters = 0) {
  MyGameBuilder builder_(_fbb);
  builder_.add_Characters(Characters);
  builder_.add_Characters_type(Characters_type);
  return builder_.Finish();
}

flatbuffers::Offset<MyGame> CreateMyGame(flatbuffers::FlatBufferBuilder &_fbb, const MyGameT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace MyGame

namespace weapons {

inline GunT *Gun::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<weapons::GunT> _o = std::unique_ptr<weapons::GunT>(new GunT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Gun::UnPackTo(GunT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = damage(); _o->damage = _e; }
  { auto _e = bool_(); _o->bool_ = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = names(); if (_e) { _o->names.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->names[_i] = _e->Get(_i)->str(); } } }
}

inline flatbuffers::Offset<Gun> Gun::Pack(flatbuffers::FlatBufferBuilder &_fbb, const GunT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGun(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Gun> CreateGun(flatbuffers::FlatBufferBuilder &_fbb, const GunT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const GunT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _damage = _o->damage;
  auto _bool_ = _o->bool_;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _names = _o->names.size() ? _fbb.CreateVectorOfStrings(_o->names) : 0;
  return weapons::CreateGun(
      _fbb,
      _damage,
      _bool_,
      _name,
      _names);
}

inline MasterT *Master::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<weapons::MasterT> _o = std::unique_ptr<weapons::MasterT>(new MasterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Master::UnPackTo(MasterT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline flatbuffers::Offset<Master> Master::Pack(flatbuffers::FlatBufferBuilder &_fbb, const MasterT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMaster(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Master> CreateMaster(flatbuffers::FlatBufferBuilder &_fbb, const MasterT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const MasterT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return weapons::CreateMaster(
      _fbb);
}

}  // namespace weapons

namespace MyGame {
namespace Sample {

inline MonsterT *Monster::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<MyGame::Sample::MonsterT> _o = std::unique_ptr<MyGame::Sample::MonsterT>(new MonsterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Monster::UnPackTo(MonsterT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = pos(); if (_e) _o->pos = std::unique_ptr<MyGame::Sample::Vec3>(new MyGame::Sample::Vec3(*_e)); }
  { auto _e = mana(); _o->mana = _e; }
  { auto _e = hp(); _o->hp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = names(); if (_e) { _o->names.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->names[_i] = _e->Get(_i)->str(); } } }
  { auto _e = inventory(); if (_e) { _o->inventory.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->inventory[_i] = _e->Get(_i); } } }
  { auto _e = color(); _o->color = _e; }
  { auto _e = weapons(); if (_e) { _o->weapons.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->weapons[_i] = std::unique_ptr<MyGame::Sample::WeaponT>(_e->Get(_i)->UnPack(_resolver)); } } }
  { auto _e = equipped_type(); _o->equipped.type = _e; }
  { auto _e = equipped(); if (_e) _o->equipped.value = MyGame::Sample::EquipmentUnion::UnPack(_e, equipped_type(), _resolver); }
  { auto _e = path(); if (_e) { _o->path.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->path[_i] = *_e->Get(_i); } } }
}

inline flatbuffers::Offset<Monster> Monster::Pack(flatbuffers::FlatBufferBuilder &_fbb, const MonsterT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMonster(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Monster> CreateMonster(flatbuffers::FlatBufferBuilder &_fbb, const MonsterT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const MonsterT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _pos = _o->pos ? _o->pos.get() : 0;
  auto _mana = _o->mana;
  auto _hp = _o->hp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _names = _o->names.size() ? _fbb.CreateVectorOfStrings(_o->names) : 0;
  auto _inventory = _o->inventory.size() ? _fbb.CreateVector(_o->inventory) : 0;
  auto _color = _o->color;
  auto _weapons = _o->weapons.size() ? _fbb.CreateVector<flatbuffers::Offset<MyGame::Sample::Weapon>> (_o->weapons.size(), [](size_t i, _VectorArgs *__va) { return CreateWeapon(*__va->__fbb, __va->__o->weapons[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _equipped_type = _o->equipped.type;
  auto _equipped = _o->equipped.Pack(_fbb);
  auto _path = _o->path.size() ? _fbb.CreateVectorOfStructs(_o->path) : 0;
  return MyGame::Sample::CreateMonster(
      _fbb,
      _pos,
      _mana,
      _hp,
      _name,
      _names,
      _inventory,
      _color,
      _weapons,
      _equipped_type,
      _equipped,
      _path);
}

inline WeaponT *Weapon::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<MyGame::Sample::WeaponT> _o = std::unique_ptr<MyGame::Sample::WeaponT>(new WeaponT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Weapon::UnPackTo(WeaponT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = damage(); _o->damage = _e; }
}

inline flatbuffers::Offset<Weapon> Weapon::Pack(flatbuffers::FlatBufferBuilder &_fbb, const WeaponT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateWeapon(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Weapon> CreateWeapon(flatbuffers::FlatBufferBuilder &_fbb, const WeaponT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const WeaponT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _damage = _o->damage;
  return MyGame::Sample::CreateWeapon(
      _fbb,
      _name,
      _damage);
}

}  // namespace Sample

inline MyGameT *MyGame::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<MyGame::MyGameT> _o = std::unique_ptr<MyGame::MyGameT>(new MyGameT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MyGame::UnPackTo(MyGameT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = Characters_type(); _o->Characters.type = _e; }
  { auto _e = Characters(); if (_e) _o->Characters.value = MyGame::CharacterUnion::UnPack(_e, Characters_type(), _resolver); }
}

inline flatbuffers::Offset<MyGame> MyGame::Pack(flatbuffers::FlatBufferBuilder &_fbb, const MyGameT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMyGame(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<MyGame> CreateMyGame(flatbuffers::FlatBufferBuilder &_fbb, const MyGameT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const MyGameT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _Characters_type = _o->Characters.type;
  auto _Characters = _o->Characters.Pack(_fbb);
  return MyGame::CreateMyGame(
      _fbb,
      _Characters_type,
      _Characters);
}

namespace Sample {

inline bool VerifyEquipment(flatbuffers::Verifier &verifier, const void *obj, Equipment type) {
  switch (type) {
    case Equipment_NONE: {
      return true;
    }
    case Equipment_MuLan: {
      auto ptr = reinterpret_cast<const MyGame::Sample::Weapon *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Equipment_Weapon: {
      auto ptr = reinterpret_cast<const MyGame::Sample::Weapon *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Equipment_Gun: {
      auto ptr = reinterpret_cast<const weapons::Gun *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyEquipmentVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEquipment(
        verifier,  values->Get(i), types->GetEnum<Equipment>(i))) {
      return false;
    }
  }
  return true;
}

inline void *EquipmentUnion::UnPack(const void *obj, Equipment type, const flatbuffers::resolver_function_t *resolver) {
  switch (type) {
    case Equipment_MuLan: {
      auto ptr = reinterpret_cast<const MyGame::Sample::Weapon *>(obj);
      return ptr->UnPack(resolver);
    }
    case Equipment_Weapon: {
      auto ptr = reinterpret_cast<const MyGame::Sample::Weapon *>(obj);
      return ptr->UnPack(resolver);
    }
    case Equipment_Gun: {
      auto ptr = reinterpret_cast<const weapons::Gun *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline flatbuffers::Offset<void> EquipmentUnion::Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher) const {
  switch (type) {
    case Equipment_MuLan: {
      auto ptr = reinterpret_cast<const MyGame::Sample::WeaponT *>(value);
      return CreateWeapon(_fbb, ptr, _rehasher).Union();
    }
    case Equipment_Weapon: {
      auto ptr = reinterpret_cast<const MyGame::Sample::WeaponT *>(value);
      return CreateWeapon(_fbb, ptr, _rehasher).Union();
    }
    case Equipment_Gun: {
      auto ptr = reinterpret_cast<const weapons::GunT *>(value);
      return CreateGun(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline EquipmentUnion::EquipmentUnion(const EquipmentUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Equipment_MuLan: {
      value = new MyGame::Sample::WeaponT(*reinterpret_cast<MyGame::Sample::WeaponT *>(u.value));
      break;
    }
    case Equipment_Weapon: {
      value = new MyGame::Sample::WeaponT(*reinterpret_cast<MyGame::Sample::WeaponT *>(u.value));
      break;
    }
    case Equipment_Gun: {
      value = new weapons::GunT(*reinterpret_cast<weapons::GunT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void EquipmentUnion::Reset() {
  switch (type) {
    case Equipment_MuLan: {
      auto ptr = reinterpret_cast<MyGame::Sample::WeaponT *>(value);
      delete ptr;
      break;
    }
    case Equipment_Weapon: {
      auto ptr = reinterpret_cast<MyGame::Sample::WeaponT *>(value);
      delete ptr;
      break;
    }
    case Equipment_Gun: {
      auto ptr = reinterpret_cast<weapons::GunT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Equipment_NONE;
}

}  // namespace Sample

inline bool VerifyCharacter(flatbuffers::Verifier &verifier, const void *obj, Character type) {
  switch (type) {
    case Character_NONE: {
      return true;
    }
    case Character_weapon: {
      auto ptr = reinterpret_cast<const weapons::Gun *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Character_Monster: {
      auto ptr = reinterpret_cast<const MyGame::Sample::Monster *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyCharacterVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCharacter(
        verifier,  values->Get(i), types->GetEnum<Character>(i))) {
      return false;
    }
  }
  return true;
}

inline void *CharacterUnion::UnPack(const void *obj, Character type, const flatbuffers::resolver_function_t *resolver) {
  switch (type) {
    case Character_weapon: {
      auto ptr = reinterpret_cast<const weapons::Gun *>(obj);
      return ptr->UnPack(resolver);
    }
    case Character_Monster: {
      auto ptr = reinterpret_cast<const MyGame::Sample::Monster *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline flatbuffers::Offset<void> CharacterUnion::Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher) const {
  switch (type) {
    case Character_weapon: {
      auto ptr = reinterpret_cast<const weapons::GunT *>(value);
      return CreateGun(_fbb, ptr, _rehasher).Union();
    }
    case Character_Monster: {
      auto ptr = reinterpret_cast<const MyGame::Sample::MonsterT *>(value);
      return CreateMonster(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline CharacterUnion::CharacterUnion(const CharacterUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Character_weapon: {
      value = new weapons::GunT(*reinterpret_cast<weapons::GunT *>(u.value));
      break;
    }
    case Character_Monster: {
      FLATBUFFERS_ASSERT(false);  // MyGame::Sample::MonsterT not copyable.
      break;
    }
    default:
      break;
  }
}

inline void CharacterUnion::Reset() {
  switch (type) {
    case Character_weapon: {
      auto ptr = reinterpret_cast<weapons::GunT *>(value);
      delete ptr;
      break;
    }
    case Character_Monster: {
      auto ptr = reinterpret_cast<MyGame::Sample::MonsterT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Character_NONE;
}

inline const MyGame::MyGame *GetMyGame(const void *buf) {
  return flatbuffers::GetRoot<MyGame::MyGame>(buf);
}

inline const MyGame::MyGame *GetSizePrefixedMyGame(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<MyGame::MyGame>(buf);
}

inline const char *MyGameIdentifier() {
  return "MGME";
}

inline bool MyGameBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, MyGameIdentifier());
}

inline bool VerifyMyGameBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MyGame::MyGame>(MyGameIdentifier());
}

inline bool VerifySizePrefixedMyGameBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MyGame::MyGame>(MyGameIdentifier());
}

inline void FinishMyGameBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MyGame::MyGame> root) {
  fbb.Finish(root, MyGameIdentifier());
}

inline void FinishSizePrefixedMyGameBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MyGame::MyGame> root) {
  fbb.FinishSizePrefixed(root, MyGameIdentifier());
}

inline std::unique_ptr<MyGame::MyGameT> UnPackMyGame(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MyGame::MyGameT>(GetMyGame(buf)->UnPack(res));
}

inline std::unique_ptr<MyGame::MyGameT> UnPackSizePrefixedMyGame(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MyGame::MyGameT>(GetSizePrefixedMyGame(buf)->UnPack(res));
}

}  // namespace MyGame

#endif  // FLATBUFFERS_GENERATED_MYGAME_MYGAME_H_
