# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MyGame

class Character(object):
    NONE = 0
    weapon = 1
    Monster = 2


def CharacterCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Character().weapon:
        import weapons.Gun
        return weapons.Gun.GunT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Character().Monster:
        import MyGame.Sample.Monster
        return MyGame.Sample.Monster.MonsterT.InitFromBuf(table.Bytes, table.Pos)
    return None
