// automatically generated by the FlatBuffers compiler, do not modify

package MyGame;

public final class Character {
  private Character() { }
  public static final byte NONE = 0;
  public static final byte weapon = 1;
  public static final byte Monster = 2;

  public static final String[] names = { "NONE", "weapon", "Monster", };

  public static String name(int e) { return names[e]; }
}

