# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample

class Equipment(object):
    NONE = 0
    MuLan = 1
    Weapon = 2
    Gun = 3


def EquipmentCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Equipment().MuLan:
        import MyGame.Sample.Weapon
        return MyGame.Sample.Weapon.WeaponT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Equipment().Weapon:
        import MyGame.Sample.Weapon
        return MyGame.Sample.Weapon.WeaponT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Equipment().Gun:
        import weapons.Gun
        return weapons.Gun.GunT.InitFromBuf(table.Bytes, table.Pos)
    return None
