// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

public final class Equipment {
  private Equipment() { }
  public static final byte NONE = 0;
  public static final byte MuLan = 1;
  public static final byte Weapon = 2;
  public static final byte Gun = 3;

  public static final String[] names = { "NONE", "MuLan", "Weapon", "Gun", };

  public static String name(int e) { return names[e]; }
}

